#!/bin/bash
# ----------------------------------------------Basisansatz 	----------------------------------------------------------------#
# |					Komprimiert alle Daten									|
# |				Auflisten alle Dateien aus Input Pfade ( mit command ls)					|
# ------------------------------------------------------------------------------------------------------------------------------#
read -p "Pfade von Collection / Datei zur Komprimierung : " Path
echo " .......... Komprimierungsprozess beginn ............ "

# ------------------------------------------------------- BEGIN Programm -------------------------------------------------

#Path="/home/irobot/Desktop/FTPSource/home/irods/FTPResc2/"

# Schritt 1 : Listet Datei nacheinander und weist die Größe der Datei dem Variable zu und gibt sie aus.

declare -i win
win=0

# declaration of variable origsize and zipsize
declare -i origsize
declare -i zipsize
sumfile=0
temp='.gz'	
# search all file and execute compress file after file
for f in $(find $Path -iname '*.*' )
do
			echo " *********************** "
			echo "$sumfile : FileName : $f"
	# get origsize
			let origsize=`stat -c "%s" $f`
			echo " -> Original Size = $origsize "
	# zip file with gzip
			gzip $f
	# get zipsize
			echo " -> New Zip Name : $f$temp"
			let zipsize=`stat -c "%s" $f$temp`
			echo " -> Zip Size = $zipsize " 
	# calculate new won capacity
			let "win += origsize - zipsize"
			echo " -> Win : $win"
	# sum of all executed (compressed) files
			let sumfile++
done

echo "-------------------------------------------------------------------------"
echo "Glückwunsch,$win freie Speicherkapazität gewonnen. "
echo "Anzahl der ZipFile : $sumfile"
echo "-------------------------------------------------------------------------"

