#!/bin/bash

/home/irobot/Dropbox/DA/Themen/Thema\ Verwaltung\ verteilter\ Speicherkapazität\ für\ wissenschaftliche\ Daten\ mit\ iRODS/Implementierung/shell/./irodsunlink
/home/irobot/Dropbox/DA/Themen/Thema\ Verwaltung\ verteilter\ Speicherkapazität\ für\ wissenschaftliche\ Daten\ mit\ iRODS/Implementierung/shell/./createRepl
